Brightspace/node-auth

package.json, test/key-generator.js, test/public-key-store.js
sinon@2 incorporates the behaviour sinon-as-promised provides
=> deps: update to sinon 2

src/core-key-generator.js, src/index.js, src/key-generator.js, test/core-key-generator.js, test/key-generator.js
Refactoring + exposing `CoreKeyGenerator`
=> Separated key rotation and key generation logic

package.json
=> chore(package): update eslint-config-brightspace to version 0.3.1

packages/node_modules/brightspace-auth-assertions/src/index.js
I thought this was the case already when I imported it, but obviously I suck at reading
=> assertions: use util.inherits

packages/node_modules/brightspace-auth-assertions/README.md, packages/node_modules/brightspace-auth-assertions/spec/impersonation.spec.js, packages/node_modules/brightspace-auth-assertions/src/errors.js, packages/node_modules/brightspace-auth-assertions/src/index.js
Orig: https://github.com/Brightspace/node-auth-assertions/pull/9
=> add impersonation checks

packages/node_modules/brightspace-auth-validation/spec/validation.spec.js, packages/node_modules/brightspace-auth-validation/src/index.js
Closes: https://github.com/Brightspace/node-auth/issues/42
PR-URL: https://github.com/Brightspace/node-auth/pull/103
=> brightspace-auth-validation: respect exp field on jwk

packages/node_modules/brightspace-auth-validation/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/104
=> brightspace-auth-validation: split _updatePublicKeys

bin/set-dependencies.js, packages/node_modules/brightspace-auth-assertions/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/105
=> chore: lint

packages/node_modules/brightspace-auth-assertions/src/errors.js, packages/node_modules/brightspace-auth-assertions/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/106
=> assertions: modernize

packages/node_modules/brightspace-auth-assertions/spec/contexts.spec.js, packages/node_modules/brightspace-auth-assertions/src/errors.js, packages/node_modules/brightspace-auth-assertions/src/index.js, packages/node_modules/brightspace-auth-token/README.md, packages/node_modules/brightspace-auth-token/spec/contexts.spec.js, packages/node_modules/brightspace-auth-token/src/contexts.js, packages/node_modules/brightspace-auth-token/src/index.js
assertions: improve context error message
Closes: https://github.com/Brightspace/node-auth/issues/41
PR-URL: https://github.com/Brightspace/node-auth/pull/107
=> assertions, token: use strings to refer to context types

package.json, packages/node_modules/brightspace-auth-keys/test/core-key-generator.js, packages/node_modules/brightspace-auth-keys/test/key-generator.js, packages/node_modules/brightspace-auth-provisioning/src/abstract-provisioning-cache.js, packages/node_modules/brightspace-auth-provisioning/src/index.js, packages/node_modules/brightspace-auth-token/spec/cacheKey.spec.js
PR-URL: https://github.com/Brightspace/node-auth/pull/111
=> refact: replace xtend usage

packages/node_modules/brightspace-auth-keys/src/ec-key-generator.js, packages/node_modules/brightspace-auth-keys/src/rsa-key-generator.js, packages/node_modules/brightspace-auth-keys/test/ec-key-generator.js, packages/node_modules/brightspace-auth-keys/test/rsa-key-generator.js, packages/node_modules/brightspace-auth-provisioning/src/index.js, packages/node_modules/brightspace-auth-validation/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/113
=> keys, provisioning, validation: use KeyObjects

packages/node_modules/brightspace-auth-provisioning/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/114
=> provisioning: require keys have "alg"

package.json, packages/node_modules/brightspace-auth-validation/spec/validation.spec.js
PR-URL: https://github.com/Brightspace/node-auth/pull/116
=> validation, test: update key generation to reduce dependencies

packages/node_modules/brightspace-auth-token/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/117
=> token: remove unnecessary context getter

packages/node_modules/brightspace-auth-token/src/index.js
PR-URL: https://github.com/Brightspace/node-auth/pull/118
=> token: make BrightspaceAuthToken a class

packages/node_modules/brightspace-auth-keys/src/key-generator.js
Ref: https://github.com/Brightspace/node-auth/issues/67
PR-URL: https://github.com/Brightspace/node-auth/pull/123
=> keys: back off when retrying key generation

package.json, packages/node_modules/brightspace-auth-keys/src/core-key-generator.js, packages/node_modules/brightspace-auth-provisioning/src/index.js, packages/node_modules/brightspace-auth-token/spec/cacheKey.spec.js
=> *: replace uuid usage

package.json, packages/node_modules/brightspace-auth-validation/src/index.js
=> validation: replace jwk-to-pem usage

package.json, packages/node_modules/brightspace-auth-keys/src/ec-key-generator.js, packages/node_modules/brightspace-auth-keys/src/rsa-key-generator.js, packages/node_modules/brightspace-auth-validation/spec/validation.spec.js
=> *: replace @trust/keyto usage

.github/workflows/build.yaml, package.json, packages/node_modules/brightspace-auth-validation/spec/validation.spec.js, packages/node_modules/brightspace-auth-validation/src/errors.js, packages/node_modules/brightspace-auth-validation/src/index.js
=> validation: replace jsonwebtoken/jws usage

.github/workflows/build.yaml
=> build: test on node 24

package.json, packages/node_modules/brightspace-auth-provisioning/src/index.js
=> provisioning: replace superagent usage

.github/workflows/build.yaml
=> build: publish with node 24

packages/node_modules/brightspace-auth-assertions/README.md, packages/node_modules/brightspace-auth-keys-dynamodb-store/README.md, packages/node_modules/brightspace-auth-keys-redis-store/README.md, packages/node_modules/brightspace-auth-keys/README.md, packages/node_modules/brightspace-auth-provisioning/README.md, packages/node_modules/brightspace-auth-token/README.md, packages/node_modules/brightspace-auth-validation/README.md
=> docs: update READMEs
